apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: dev
  name: myapp-deploy
spec:
  replicas: 13
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: web
        image: quay.io/pranavadmin/ecom:v1    
