apiVersion: v1
kind: Pod
metadata:
  name: webserver
spec:
  containers:
  - name: webapp
    image: quay.io/pranavadmin/ecom:v1
    imagePullPolicy: IfNotPresent  
    securityContext:
      capabilities:
        add: ["CAP_NET_RAW"]
