apiVersion: v1
kind: Pod
metadata:
  namespace: dev
  name: db
  labels:
    app: db
spec:
  containers:
  - name: webapp
    image: pranavadmin/ecom-web:v2
    imagePullPolicy: IfNotPresent  
    securityContext:
      capabilities:
        add: ["CAP_NET_RAW"]
