apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: myrs3
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nfs
  template:
    metadata:
      labels:
        app: nfs
    spec:
      containers:
      - name: web
        image: quay.io/pranavadmin/ecom:v1 
